  pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - './etc-pihole:/etc/pihole'
      # - ${USERDIR}/docker/pihole/pihole.log:/var/log/pihole.log
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    environment:
      - ServerIP='192.168.1.76'
      - TZ='America/Los_Angeles'
      - WEBPASSWORD='Gyh1997127.'
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1

